In [1]:
import sys
sys.path.append('/Users/erikweilandt/Library/Caches/pypoetry/virtualenvs/tepem-FeojsIC2-py3.11/lib/python3.11/site-packages')

In [2]:
import numpy as np

In [43]:
num_slice = 4

In [44]:
x = np.linspace(0, 10, 2* num_slice + 1)
x

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [45]:
y = np.array([foo*2 for foo in x ])
y

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. ])

In [46]:
total = np.vstack((x,y)).T
total

array([[ 0.  ,  0.  ],
       [ 1.25,  2.5 ],
       [ 2.5 ,  5.  ],
       [ 3.75,  7.5 ],
       [ 5.  , 10.  ],
       [ 6.25, 12.5 ],
       [ 7.5 , 15.  ],
       [ 8.75, 17.5 ],
       [10.  , 20.  ]])

In [52]:
ltg = np.arange(0, 2*num_slice+1)
ltg

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [60]:
ltg2 = np.arange(2*num_slice+1, 4*num_slice+2)
ltg2

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17])

In [58]:
mod = np.ones(2*num_slice+1, dtype= int)
for i, num in enumerate(mod, 1):
    if i%2==0:
        mod[i] +=1
    mod[-1] = 1
ltg_edit = np.repeat(ltg, mod).reshape((num_slice, 3))
ltg_edit

array([[0, 1, 2],
       [2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [62]:
ltg_edit2 = np.repeat(ltg2, mod).reshape((num_slice, 3))
ltg_edit2

array([[ 9, 10, 11],
       [11, 12, 13],
       [13, 14, 15],
       [15, 16, 17]])

In [63]:
for slab in ltg_edit:
    print(slab)

[0 1 2]
[2 3 4]
[4 5 6]
[6 7 8]
